name = "ReverseSearch"
uuid = "4c89c464-f98c-4bab-a6f2-360512b03a4e"
authors = ["Maximilian Hübl <maximilian.huebl@ist.ac.at>"]
version = "0.1.0"

[extras]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Graphs"]